### ISSUE TITLE
Custom colors do not apply

### ISSUE THREAD

**Issue by Nargle30** [onfido/react-native-sdk#10]
**iOS:** 
Custom colors work fine on simulator, but don't work on real devises

**Android:** 
To see custom colors I need to run command _npm --prefix node_modules/@onfido/react-native-sdk/ run updateColors_ every time after cleaning the project. Is this expected behavior?

What I use:
"react-native": "0.61.0",
"react": "16.9.0",

To use custom colors I created file colors.json on the same level as package.json
```
{
    "onfidoPrimaryColor": "#XXXXXX",
    "onfidoPrimaryButtonTextColor": "#XXXXXX",
    "onfidoPrimaryButtonColorPressed": "#XXXXXX",
    ...
}
```

**Comment by keremgund** [comment]
Hi @Nargle30 , 
I was able to reproduce the issue and will let you know once we make any progress about fixing it.

Thanks for reporting the issue and sorry for the inconvenience,
Kerem

**Comment by Nargle30** [comment]
Hello @keremgund, do you have any updates on this issue?

**Comment by keremgund** [comment]
Hello @Nargle30 ,
We're in testing stage now and aiming to deliver fix by the end of next week.

Thanks for your patience,
Kerem

**Comment by Nargle30** [comment]
Hello @keremgund ,

Thank you for the new release, the issue is resolved.
 
Best,
Daria

**Comment by Nargle30** [comment]
@keremgund One last question. Does it make sense to add 'npm --prefix node_modules/@onfido/react-native-sdk/ run updateOnfido' to package.json as a postinstall script?

**Comment by keremgund** [comment]
Hello @Nargle30 ,
Yes its still needed for android.

Kerem
