### ISSUE TITLE
No suitable constructor found for FaceCaptureStep error when upgrading to 7.0.0 - Android

### ISSUE THREAD

**Issue by mateoguzmana** [onfido/react-native-sdk#104]
I'm getting the following error when trying to upgrade `@onfido/react-native-sdk` to the version 7.0.0.

![image](https://user-images.githubusercontent.com/20783123/203555378-4009e200-e3cd-42a7-a2b9-af980027f202.png)

![image](https://user-images.githubusercontent.com/20783123/203555924-3794cdc0-e96b-4d15-8dc4-1610cc15bbcc.png)

**Comment by PedrinhoDS** [comment]
Hey @mateoguzmana, I'm closing this issue since it was fixed in the latest release.
