### ISSUE TITLE
Getting Unexpected result Intent after backgrounding/foregrounding app while in Onfido flow

### ISSUE THREAD

**Issue by lochness42** [onfido/react-native-sdk#11]
We're getting: `Unexpected result Intent. It might be a result of incorrect integration, make sure you only pass Onfido intent to handleActivityResult. It might be due to unpredictable crash or error. Please report the problem to android-sdk@onfido.com. Intent: null 
 resultCode: 0`
It happens for us when we background app on the document capture step and then foregrounding it again. Do you have any suggestion how to track down what could go wrong?
Onfido version used is `com.onfido.sdk.capture:onfido-capture-sdk:7.2.0`

Thank you.

**Comment by gokhanaliccii** [comment]
Hi @lochness42,

Could you answer the below questions to help us to diagnose the problem?

- Can you share the SDK initialization code?

- Does the problem whether permanently or intermittently occurs?

- Does the problem occurs also on the different version of the [Android SDK](https://github.com/onfido/onfido-android-sdk/tags) (7.1.0, 7.0.0..)?

- Was the proguard enabled?

- Did you get the `Unexpected result Intent. It might be a result...` error after completion of the flow or after background to foreground?

**Comment by burakeregar** [comment]
Closing the issue due to inactivity.
