### ISSUE TITLE
TypeError: null is not an object(evaluating 'OnfidoSdk.start') getting this issue on android.

### ISSUE THREAD

**Issue by manpreetsingh3215** [onfido/react-native-sdk#12]
"react-native": "0.62.2",
"@onfido/react-native-sdk": "^1.3.0",
this is working fine on IOS , but have issue with android 
actually OnfidoSdk is coming null from the NativeModules in the onfido.js file in the module
how can i resolve this issue.Please help!

**Comment by gokhanaliccii** [comment]
Hi @manpreetsingh3215 ,

I've tried to reproduce the error on a test project following steps but I didn't come across the error 

```
1) npx react-native init TestProject --version 0.62.2
 
2) cd TestProject

3) npm install @onfido/react-native-sdk --save

4) npm --prefix node_modules/@onfido/react-native-sdk/ run updateBuildGradle

5) Created sdkToken to use in the next step, https://github.com/onfido/react-native-sdk#3-configuring-sdk-with-tokens
 
6) Replaced App.json with sample code snippet at https://github.com/onfido/react-native-sdk#usage   

7) npx react-native run-android 

```

Can you please share more information to reproduce the issue?

**Comment by manpreetsingh3215** [comment]
hey @gokhanaliccii , thanks for the reply
previously i had an issue with the android manifest.xml file to run app 
even i had posted this too. https://github.com/onfido/react-native-sdk/issues/7 
and anyhow had got it resolved. 
i observed one thing that i did some changes
android:allowBackup="true"
android:supportsRtl="true"
android:appComponentFactory="android.support.v4.app.CoreComponentFactory"
 tools:replace="android:supportsRtl, android:appComponentFactory, allowBackup">
as i need android:allowBackup="true" to be true for other modules, but onfido , is using 
android:supportsRtl="false", that is the only difference i observed since i installed this module.

could you please confirm that , whether i am doing something wrong in the app manifest file or not ?

**Comment by manpreetsingh3215** [comment]
hey @gokhanaliccii , thanks for the reply previously i had an issue with the android manifest.xml file to run app even i had posted this too. #7 and anyhow had got it resolved. i observed one thing that i did some changes android:allowBackup="true" android:supportsRtl="true" android:appComponentFactory="android.support.v4.app.CoreComponentFactory" tools:replace="android:supportsRtl, android:appComponentFactory, allowBackup"> as i need android:allowBackup="true" to be true for other modules, but onfido , is using android:supportsRtl="false", that is the only difference i observed since i installed this module.
could you please confirm that , whether i am doing something wrong in the app manifest file or not ?

**Comment by manpreetsingh3215** [comment]
now , i am trying to create a new standalone project and will implement onfido in that and let you know , whether it works or not

**Comment by manpreetsingh3215** [comment]
with the standalone project , it is working fine

**Comment by gokhanaliccii** [comment]
I don't think above manifest properties would cause that kind error you might try cleaning cache files or 
compare hermes related settings between your project and a new project to check if there is a difference.

**Comment by manpreetsingh3215** [comment]
hi @gokhanaliccii , i tried it , but i dint get any difference there in both projects , since this sdk supports auto-linking only , i had doubt of linking , i did it manually by adding 
import com.onfido.reactnative.sdk.OnfidoSdkPackage;
in MainApplication.java and 
new OnfidoSdkPackage() in getPackages methods in the same file 
and it worked :)
thanks for the support
