### ISSUE TITLE
SDK causes app to crash on iOS14 - dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib

### ISSUE THREAD

**Issue by keithharrisonuk** [onfido/react-native-sdk#13]
### What was the expected behaviour?

App launches

### What happened instead?
App crashes.

Logs:
`dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib`

- Onfido SDK (Debug/Release): Both
- iOS: 14.0
- Xcode: 12.0
- Device/Simulator: Simulator iPhone X

### Steps to reproduce:

- Create react native app
- Install onfido/react-native-sdk
- Run on simulator with iOS 14 installed.

### Notes
I think this is the cause...
 - https://github.com/onfido/onfido-ios-sdk/issues/180

...and upgrading the onfido-ios-sdk to 18.6.0 will fix it?

**Comment by Nargle30** [comment]
Same issue

**Comment by smohamedjavid** [comment]
@keithharrisonuk Yes, upgrading the iOS SDK to v18.6.0 solves the problem. But we cannot install it coz it'll conflict with the library. The Onfido team is looking into the issue and soon will be releasing a new version. A PR [#14 ](https://github.com/onfido/react-native-sdk/pull/14) has been made to resolve this.

**Comment by keremgund** [comment]
Hi all,
We have published react-native-sdk [1.3.2](https://github.com/onfido/react-native-sdk/releases/tag/v1.3.2) version to fix this problem

**Comment by smohamedjavid** [comment]
@keremgund Thanks, The issue is resolved with the latest version 1.3.2. I had tested it out on iOS 14 Simulators.

**Comment by keithharrisonuk** [comment]
Thanks @keremgund I can confirm this is working. Thanks for the speedy fix.
