### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by alireza847-programmer** [onfido/react-native-sdk#15]
Ld /Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Urbanq.app/Urbanq normal (in target 'Urbanq' from project 'Urbanq')
    cd /Users/alireza/Desktop/urbanq-native-application/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios10.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/BVLinearGradient -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/DoubleConversion -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/FBReactNativeSpec -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-DoubleConversion -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-Folly -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-Glog -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-PeerTalk -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-RSocket -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/FlipperKit -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Folly -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RCTTypeSafety -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNCAsyncStorage -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNCMaskedView -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNFastImage -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNGestureHandler -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNReanimated -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNSVG -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNScreens -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNVectorIcons -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-Core -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-CoreModules -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTAnimation -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTBlob -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTImage -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTLinking -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTNetwork -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTSettings -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTText -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTVibration -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-cxxreact -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-jsi -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-jsiexecutor -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-jsinspector -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/ReactCommon -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/ReactNativeART -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/SDWebImage -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/SDWebImageWebPCoder -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Toast -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Yoga -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/YogaKit -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/glog -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/libwebp -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/onfido-react-native-sdk -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-geolocation -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-geolocation-service -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-maps -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-safe-area-context -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-simple-toast -L/Users/alireza/Desktop/urbanq-native-application/ios/Pods/CocoaLibEvent/lib -L/Users/alireza/Desktop/urbanq-native-application/ios/Pods/OpenSSL-Universal/ios/lib -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/BVLinearGradient -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/DoubleConversion -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/FBReactNativeSpec -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-DoubleConversion -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-Folly -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-Glog -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-PeerTalk -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Flipper-RSocket -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/FlipperKit -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Folly -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RCTTypeSafety -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNCAsyncStorage -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNCMaskedView -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNFastImage -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNGestureHandler -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNReanimated -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNSVG -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNScreens -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/RNVectorIcons -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-Core -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-CoreModules -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTAnimation -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTBlob -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTImage -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTLinking -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTNetwork -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTSettings -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTText -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-RCTVibration -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-cxxreact -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-jsi -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-jsiexecutor -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/React-jsinspector -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/ReactCommon -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/ReactNativeART -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/SDWebImage -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/SDWebImageWebPCoder -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Toast -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Yoga -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/YogaKit -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/glog -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/libwebp -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/onfido-react-native-sdk -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-geolocation -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-geolocation-service -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-maps -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-safe-area-context -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/react-native-simple-toast -L/Users/alireza/Desktop/urbanq-native-application/ios/Pods/CocoaLibEvent/lib -L/Users/alireza/Desktop/urbanq-native-application/ios/Pods/OpenSSL-Universal/ios/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator -F/Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator -F/Users/alireza/Desktop/urbanq-native-application/ios/Pods/Onfido -filelist /Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Intermediates.noindex/Urbanq.build/Debug-iphonesimulator/Urbanq.build/Objects-normal/x86_64/Urbanq.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Intermediates.noindex/Urbanq.build/Debug-iphonesimulator/Urbanq.build/Objects-normal/x86_64/Urbanq_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lBVLinearGradient -lCocoaAsyncSocket -lDoubleConversion -lFBReactNativeSpec -lFlipper -lFlipper-DoubleConversion -lFlipper-Folly -lFlipper-Glog -lFlipper-PeerTalk -lFlipper-RSocket -lFlipperKit -lFolly -lRCTTypeSafety -lRNCAsyncStorage -lRNCMaskedView -lRNFastImage -lRNGestureHandler -lRNReanimated -lRNSVG -lRNScreens -lRNVectorIcons -lReact-Core -lReact-CoreModules -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReactCommon -lReactNativeART -lSDWebImage -lSDWebImageWebPCoder -lToast -lYoga -lYogaKit -lcrypto -levent -levent_core -levent_extra -levent_pthreads -lglog -llibwebp -lonfido-react-native-sdk -lreact-native-geolocation -lreact-native-geolocation-service -lreact-native-maps -lreact-native-safe-area-context -lreact-native-simple-toast -lssl -lstdc++ -framework AVFoundation -framework AudioToolbox -framework CFNetwork -framework Foundation -framework ImageIO -framework JavaScriptCore -framework MobileCoreServices -framework Onfido -framework QuartzCore -framework Security -framework UIKit -ObjC -lc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Intermediates.noindex/Urbanq.build/Debug-iphonesimulator/Urbanq.build/Urbanq.app-Simulated.xcent -lPods-Urbanq -Xlinker -dependency_info -Xlinker /Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Intermediates.noindex/Urbanq.build/Debug-iphonesimulator/Urbanq.build/Objects-normal/x86_64/Urbanq_dependency_info.dat -o /Users/alireza/Library/Developer/Xcode/DerivedData/Urbanq-ftuljbyhhnbjghglebcjepsujzrr/Build/Products/Debug-iphonesimulator/Urbanq.app/Urbanq

ld: warning: Could not find or use auto-linked library 'swiftCoreML'
ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'
ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_onfido_react_native_sdk in libonfido-react-native-sdk.a(OnfidoSdk-62bff44860274be7aa1ef24914976bcb3f4e2af54601146300f9e0ceace844a2.o)
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_onfido_react_native_sdk in libonfido-react-native-sdk.a(Response.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_onfido_react_native_sdk)
  "__swift_FORCE_LOAD_$_swiftCoreMIDI", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_onfido_react_native_sdk in libonfido-react-native-sdk.a(OnfidoSdk-62bff44860274be7aa1ef24914976bcb3f4e2af54601146300f9e0ceace844a2.o)
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_onfido_react_native_sdk in libonfido-react-native-sdk.a(Response.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMIDI_$_onfido_react_native_sdk)
  "__swift_FORCE_LOAD_$_swiftCoreML", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreML_$_onfido_react_native_sdk in libonfido-react-native-sdk.a(OnfidoSdk-62bff44860274be7aa1ef24914976bcb3f4e2af54601146300f9e0ceace844a2.o)
      __swift_FORCE_LOAD_$_swiftCoreML_$_onfido_react_native_sdk in libonfido-react-native-sdk.a(Response.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreML_$_onfido_react_native_sdk)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing Recent Messages
Undefined symbol: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers

Showing Recent Messages
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreMIDI

Showing Recent Messages
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreML

**Comment by smohamedjavid** [comment]
@alireza847-programmer 

Add an empty Swift File (without briding Headers) to your project through Xcode.

**Comment by alireza847-programmer** [comment]
> @alireza847-programmer
> 
> Add an empty Swift File (without briding Headers) to your project through Xcode.

in root of project? or in iOS folder

**Comment by smohamedjavid** [comment]
@alireza847-programmer 

- Open your project in Xcode (open` YourProjectName.xcodeproj`)
- Select from Menu - File > New > File (⌘N) > Swift File > Next > `Onfido.swift` (Feel free to choose your file name) >` Don't  create headers`. 
 - Clean your build folder (From Menu - Product > Clean Build Folder (⇧⌘K))
 - Run your project now

**Comment by keremgund** [comment]
Hi @alireza847-programmer ,
Today we've released new version, can you test it out with latest version and see whether the issue disappears ?
If the issue persists, please provide Onfido SDK and Xcode version information you're using.

Thanks,
Kerem

**Comment by burakeregar** [comment]
Closing the issue due to inactivity.

**Comment by marcaaron** [comment]
This issue still occurs for what it's worth

Xode Version 12.2 (12B45b)
`@onfido/react-native-sdk`: 1.3.3

Adding the empty file fixes it
