### ISSUE TITLE
Connection Lost error

### ISSUE THREAD

**Issue by keshavashiya** [onfido/react-native-sdk#28]
![image](https://user-images.githubusercontent.com/20239068/116412302-2bc54580-a854-11eb-94cd-fea18b211792.png)

While submitting I'm getting above error

**Comment by eraxyz** [comment]
Hi @keshavashiya, can you provide more information?

- Does this happen every time?
- Is this on iOS or Android?
- What version of the React Native SDK are you using?
- What version of React Native and React are you using?

**Comment by keshavashiya** [comment]
@eraxyz 

![WhatsApp Image 2021-05-28 at 11 14 53 AM](https://user-images.githubusercontent.com/20239068/119936995-aabeb280-bfa7-11eb-920b-8400939bd5e5.jpeg)

issue is resolved in Android but getting in iOS

- Yes in iOS it's happening every time
- Onfido SDK version 1.3.3
- React Native 0.63.4 and React 16.13.1

**Comment by keshavashiya** [comment]
@lichmac are you sending correct applicationId while creating SDK token? android bundleId will be

**Comment by lichmac** [comment]
@keshavashiya Sorry my bad. Thank you very much!

**Comment by Stoneski93** [comment]
@keshavashiya Have you resolved your issue with connection timeout? I got same issue on ios simulator, android emulator and android device. It is come when I am not specify capture document.

**Comment by keshavashiya** [comment]
@Stoneski93 Yes after using correct bundleId while creating SDK token this issue got resolved.
simply use correct bundleId for each Platform then issue won't appear.

**Comment by alexbrailko** [comment]
Have the same issue (Connection lost) on android only.
"react": "17.0.2",
"react-native": "0.65.1",
 "@onfido/react-native-sdk": "2.2.0"

**Comment by keshavashiya** [comment]
closing this issue since above solutions seems working fine.
