### ISSUE TITLE
Library not loaded: @rpath/libswiftAVFoundation.dylib

### ISSUE THREAD

**Issue by k123lohar** [onfido/react-native-sdk#3]
I am trying to run iOS application in iPhone 5s which is 10.3.1 OS version but its not running and getting errors like below.

dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/abcd/Library/Developer/CoreSimulator/Devices/77A26A12-E922-1160-B857-3F05504F11FF/data/Containers/Bundle/Application/D0009F84-DCB8-2F73-ACF2-56D9CC561DA8/TestOnfido.app/Frameworks/Onfido.framework/Onfido
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for iOS simulator
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for iOS simulator

,So please anyone can help to solve this error????

**Comment by stevoland** [comment]
Hi, looking in our project, we have added the following Swift module which might help you

```swift
/*
 Onfido.swift
 This file is required to force Xcode to package Swift runtime libraries required for
 the Onfido iOS SDK to run
 */
import Foundation
import AVFoundation
import CoreImage
import UIKit
import Vision

func fixLibSwiftOnoneSupport() {
  // from https://stackoverflow.com/a/54511127/2982993
  print("Fixes dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib")
}

```

**Comment by Nargle30** [comment]
Had the same.
Solved by adding libswiftAVFoundation.tbd and libswiftUIKit.tbd
For me was useful to look into onfido-ios-sdk issues. This one for ex.: https://github.com/onfido/onfido-ios-sdk/issues/118

**Comment by anuragajwani** [comment]
Hi @k123lohar, @stevoland & @Nargle30,

Prior to iOS 12.2 Swift runtime libraries are not included within the operating system. Thus the app must include these Swift runtime libraries when packaged. 

As @stevoland mentioned including a file that imports the Swift runtime libraries can force Xcode to include these in the package. However as an alternative you can also set the build settings to force Xcode to include the Swift runtime libraries. You might still be required the file @stevoland has mentioned if your app does not make any use of Swift and Xcode might not know which Swift runtime libraries the Onfido SDK uses.

![Screenshot 2020-08-10 at 16 20 44](https://user-images.githubusercontent.com/7071488/89800317-897afb80-db26-11ea-86f5-eaab46b3bb75.png)

Let me know if this resolves your issue,
Anurag

**Comment by keremgund** [comment]
Closing the issue due to lack of response. Please open new one if you think problem persists.

Kerem
