### ISSUE TITLE
Missing withConsentStep Option

### ISSUE THREAD

**Issue by mdcuk34** [onfido/react-native-sdk#33]
Following the recommendation from @keremgund on [this](https://github.com/onfido/onfido-ios-sdk/issues/234#issuecomment-839900939) issue in the `onfido-ios-sdk` repo I'm opening this to address the missing option to pass the `withConsentStep` to the Onfido SDK. 

- @keremgund You mentioned that the React Native SDK doesn't currently point to the Onfido SDK version that includes the Consent Step however the [Podfile](https://github.com/onfido/react-native-sdk/blob/master/ios/Podfile#L7) references `Onfido 20.1` and the [docs](https://documentation.onfido.com/sdk/ios/21.1.0#consent-step) for this version state that the Consent Step is available? - _Maybe I'm miss understanding how you package this all together?_ 

Thanks for your help! 

cc: @andra-radu

**Comment by andra-radu** [comment]
@mdcuk34 The default RN installation points to iOS version 20.1.0. It needs to updated to 21.0.0 or above as the consent screen was only added in 21.0.0.

**Comment by mdcuk34** [comment]
@andra-radu Ah good spot, sorry I missed that! Is there a planned date for you to do the upgrade?

**Comment by andra-radu** [comment]
@mdcuk34 Not at the moment unfortunately.

**Comment by eraxyz** [comment]
@mdcuk34 This feature is now available in our newest release (2.0.0)

**Comment by mdcuk34** [comment]
@eraxyz Looks good and works well! Thank you!
