### ISSUE TITLE
Support for React Native 0.64

### ISSUE THREAD

**Issue by AlexHooperDev** [onfido/react-native-sdk#36]
Currently, when compiling on React Native 0.64, I get the following error:
```
The following build commands failed:
        CompileSwift normal x86_64 /Users/alex.hooper/Documents/figloo-bank-mobile/node_modules/@onfido/react-native-sdk/ios/OnfidoSdk.swift
        CompileSwift normal x86_64 /Users/alex.hooper/Documents/figloo-bank-mobile/node_modules/@onfido/react-native-sdk/ios/Response.swift
```
Everything works as intended on RN 0.63.2. Do you plan on supporting 0.64?

**Comment by andra-radu** [comment]
@AlexHooperDev -  We’ve successfully tested with 0.64.0 in the past. I would suggest the usual cleans (node_modules, caches, pod folders, etc) if you haven’t already https://github.com/pmadruga/react-native-clean-project can help with this.

**Comment by seewah** [comment]
Closing this now. Please re open if problem persists

**Comment by pouriabagheri** [comment]
similar error 
The following build commands failed:
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
        CompileSwift normal x86_64 /Users/test/app/node_modules/@onfido/react-native-sdk/ios/OnfidoSdk.swift
        CompileSwift normal x86_64 /Users/test/app/node_modules/@onfido/react-native-sdk/ios/Response.swift
(3 failures)
