### ISSUE TITLE
Does not work with gradle 6.2 for me

### ISSUE THREAD

**Issue by pektinasen** [onfido/react-native-sdk#4]
gradle task failed with

```
.\gradlew.bat installDebug

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\saski\projects\onfidoBasic\node_modules\@onfido\react-native-sdk\android\build.gradle' line: 198

* What went wrong:
A problem occurred configuring project ':onfido_react-native-sdk'.
> Cannot set the value of read-only property 'classDirectories' for task ':onfido_react-native-sdk:codeCoverageReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.

BUILD FAILED in 5s
```

I had to change the distributionUrl in gradle-wrapper.properties to:

    distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip

I'm not a gradle expert, so I don't know what the underlying issue is.

**Comment by blutig** [comment]
Hi pektinasen, ¿how are you?

If you need to use gradle version 6+ you need to change 

classDirectories = XXXXXXXXX

by

classDirectories.setFrom(XXXXXXXXX)

The both (classDirectories = or classDirectories.setFrom) work in gradle 5+

Bye,

**Comment by pektinasen** [comment]
Thanks for the reply.

I'll keep that in mind in case we have to update our gradle version.
