### ISSUE TITLE
Takes very long time to build the app after adding onfido sdk

### ISSUE THREAD

**Issue by aakashsigdel** [onfido/react-native-sdk#41]
As the title suggests, it take more than 20 minutes to build the app with `./gradlew assembleRelease` after installing onfido sdk. 

Minimal steps to reproduce:
- Create an expo app
- eject the expo app
- Build the react-native app with `./gradlew assembleRelease` (takes less than 4 minutes)
- Add onfido sdk (Following the Readme.md)
- Build the react-native app with `./gradlew assembleRelease` (takes more than 20 minutes) to build

React-native version: 0.63.4 
Expo version: 42.0.1
expo-cli version: 4.10.0
Operating system: macOS Catalina (10.15.5)
Machine: Macbook pro 2015
Processor: 2.5 GHz Quad-Core Intel core i7
Memory: 16GB DDR3

**Comment by ramprasad-parajuli** [comment]
@aakashsigdel, thank you for reaching out. 

I have responded to the Zendesk ticket that you opened, and I am providing the response here for your reference.

After trying to reproduce the issue from my end, I am confident that I found a solution that should greatly speed up your build time.

The current version of the React Native SDK is pulling the Android SDK from bintray, but the SDK team recently made the Android SDK also available from maven central, which from my testing greatly speeds up the build time.

Could you please try updating your build.gradle file at <project>/android/build.gradle by replacing the following:
`maven { url "https://dl.bintray.com/onfido/maven"}`
with:
`mavenCentral()`
and let us know if it resolves the issue for you?

I look forward to hearing from you soon.

**Comment by aakashsigdel** [comment]
@ramprasad-parajuli This did help solve the problem. Thank you
