### ISSUE TITLE
Incorrectly shown 'Camera access is denied' at the film yourself step

### ISSUE THREAD

**Issue by Julesssss** [onfido/react-native-sdk#45]
I'm stuck in a loop when testing the Onfido flow on a Pixel 2, it occurs on both the Firefox and Chrome browsers. The flow works perfectly on iOS. 

```
Device OS: Android 11
SDK version: 1.3.3
```

**Steps to reproduce**
- Trigger the Onfido SDK within our flow
- _The camera permission is already enabled_ 
- Take a photo of front and back of licence
- Land at the 'Let's make sure nobody is impersonating you' step

![Screenshot_20210924-160819](https://user-images.githubusercontent.com/10736861/134699868-15eb186a-b995-4032-bf12-7f53fcd5f8f4.png)

- Tap continue
- The Camera with face outline is displays for brief moment
- But is then replaced by the 'Camera access is denied' page

![Screenshot_20210924-160852](https://user-images.githubusercontent.com/10736861/134699898-bda94514-0c7d-4210-aac9-729298eaa4b2.png)

- Obviously, this isn't correct as I successfully uploaded photos in previous steps

**Comment by Julesssss** [comment]
I was unable to attach the short screencast, but you can [view it here](https://github.com/Expensify/App/issues/5299) as our repo is open source.

Please let me know if you need any more information.

**Comment by Julesssss** [comment]
My colleague just pointed out that the issue is not with this SDK, but with the Onfido mWeb flow. Is there a better place to raise this issue?

**Comment by Julesssss** [comment]
The issue is essentially the same as this reported issue, but it occurring in all Android browsers when using the QR code flow.

**Comment by andra-radu** [comment]
Hello @Julesssss,
The screen says “ browser settings” so should be part of the web SDK permission flow. Can we confirm what exact version of the web sdk you are using? 1.3.3 is not a version, and how exactly are you integrating?
