### ISSUE TITLE
Xcode13 error: this SDK is not supported by the compiler, while this compiler is 'Apple Swift version 5.5

### ISSUE THREAD

**Issue by gurbela** [onfido/react-native-sdk#46]
Failed to build module 'Onfido'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK.

How can this be fixed?

**Comment by jahicDario** [comment]
+1

**Comment by jahicDario** [comment]
any update on this?

**Comment by tophernuts** [comment]
@dethspikee any idea when [this fix](https://github.com/onfido/onfido-ios-sdk/issues/253#issuecomment-942114780) will be available on react-native?
The [ios-sdk release was released 29 days ago](https://github.com/onfido/onfido-ios-sdk/releases/tag/23.0.0)

**Comment by choukat** [comment]
Hello, I got the same issue did someone found a solution to fix it ?

**Comment by andra-radu** [comment]
Hello @gurbela @tophernuts @jahicDario @dethspikee @choukat - we will update the RN SDK soon, probably in a month’s time, but in mean time can you update the iOS SDK dependency to the latest SDK version (23.0.0+) which supports xcode 13 and check if the issue still persists?

**Comment by choukat** [comment]
Everything is fine with XCode 12 so don't need to change something for now, I can wait one month it's ok. Thank's for your answer.

**Comment by andra-radu** [comment]
Thank you too @choukat

**Comment by burakeregar** [comment]
React Native SDK 3.0.0 has been released. This version of the RN SDK implements iOS SDK 23.1.0 and Android SDK 10.3.2.
