### ISSUE TITLE
:onfido_react-native-sdk:codeCoverageReport

### ISSUE THREAD

**Issue by miladbruce** [onfido/react-native-sdk#5]
this version of SDK won't build on RN 0.62.2, please fix this or merge @adamivancza. thanks

**Comment by adamivancza** [comment]
@miladbruce while we're waiting on onfidio you can use my repo directly in your package.json: https://github.com/adamivancza/react-native-sdk/tree/jacoco-tmp-fix

**Comment by miladbruce** [comment]
I did 😁

**Comment by eraxyz** [comment]
Hello @miladbruce, 

This has been fixed in the latest release. Please check it out and close this issue if the problem is resolved. Thanks!

**Comment by gokhanaliccii** [comment]
@miladbruce have you had a chance to check the latest release?

**Comment by miladbruce** [comment]
@eraxyz  @gokhanaliccii  yes, it's work thank you
