### ISSUE TITLE
Bintray has been sunset

### ISSUE THREAD

**Issue by sregg** [onfido/react-native-sdk#55]
Bintray [has been sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) since May 2021.
They kept it working but we're recently getting a lot of 502 errors.

```
> Could not resolve all artifacts for configuration ':onfido_react-native-sdk:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :onfido_react-native-sdk
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

Onfido is the only library in our app still on Bintray.
Can you please move it to another Maven or another artifact management tool?

Thanks 🙏

**Comment by R4md4c** [comment]
Hey @sregg, Onfido is already being on mavenCentral(). 

There's already a [section](https://github.com/onfido/react-native-sdk#42-update-your-android-buildgradle-files) in the documentation that's talking about updating the Gradle files manually. 

Hope that helps

**Comment by gurpreet-onfido** [comment]
Hey @sregg 

bintray is now dead (they shut down their service affecting loads of libraries) like most people who moved to mavencentral. Integrator needs to do this https://github.com/onfido/onfido-android-sdk/blob/master/MIGRATION.md#changes.

There might have been some caches. If you remove https://dl.bintray.com/onfido/maven/) and have mavenCentral() instead, it will resolve the issue.

Please give this a try and let us know how it goes.

Kind regards,
Gurpreet Singh

**Comment by shaddeen** [comment]
@gurpreet-onfido I ran the `updateBuildGradle` script on the sdk version we're on (2.0.0) and with the following output:

```sh
> @onfido/react-native-sdk@2.0.0 updateBuildGradle /mobile/node_modules/@onfido/react-native-sdk
> npm run updateGradleMultiDex && npm run updateGradleMavenLink


> @onfido/react-native-sdk@2.0.0 updateGradleMultiDex /mobile/node_modules/@onfido/react-native-sdk
> node scripts/android_enable_multi_dex.js

Updated: multiDexEnabled true was added to android/app/build.gradle

> @onfido/react-native-sdk@2.0.0 updateGradleMavenLink /mobile/node_modules/@onfido/react-native-sdk
> node scripts/android_add_maven_link.js

Verified: https://dl.bintray.com/onfido/maven is already in android/build.gradle
```

`android/build.gradle`
```
allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()

        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven { url "https://dl.bintray.com/onfido/maven" } 
    }
}
```

`android/app/build.gradle`
```
defaultConfig {
        multiDexEnabled true
        ...
}
```

But then faced with this slightly similar error:

```sh
Could not determine the dependencies of task ':app:lintVitalProdRelease'.
> Could not resolve all artifacts for configuration ':app:alphaDebugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :app
         project :app > project :react-native-device-info // <-- repeated for all our RN dependencies/native modules
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

I tried using just `mavenCentral()` but I get the same error as the OP. Any suggestions?

**Comment by shaddeen** [comment]
Looks like both 2.0.0 and 2.1.0 are not in the maven repository so with Bintray sunsetting we could not get our release builds to compile, only 2.2.0 can be found on maven and we've had to upgrade to fix the issue.

**Comment by gurpreet-onfido** [comment]
Hello @shaddeen Glad to know that you were able to resolve the issue at your end. Let us know if anything is needed from our end.

Kind regards,
Gurpreet Singh
