### ISSUE TITLE
502 gateway error while building.

### ISSUE THREAD

**Issue by akshay-chicmic** [onfido/react-native-sdk#58]
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/75297772/146697290-91cf7cb5-fdf1-4201-ac6a-7dd09435137d.png">

 Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/onfido/maven/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by akshay-chicmic** [comment]
Added mavenCentral() instead of maven{url : https://dl.bintray.com/onfido/maven/}

**Comment by gurpreet-onfido** [comment]
Hello Akshay, 

Greetings for the day!

bintray is now dead (they shut down their service affecting loads of libraries) like most people who moved to mavencentral. Integrator needs to do this https://github.com/onfido/onfido-android-sdk/blob/master/MIGRATION.md#changes.

There might have been some caches. If you remove https://dl.bintray.com/onfido/maven/) and have mavenCentral() instead, it will resolve the issue.

Kind regards,
Gurpreet Singh
