### ISSUE TITLE
[v 4.0.0] Android app doesn't compile because an error: Cannot set the value of property ‘id’ of type java.lang.String using an instance of type org.apache.groovy.json.internal.LazyMap

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [onfido/react-native-sdk#60]
By Creating a brand new React Native project and following all installation steps as described  [In the documentation](https://github.com/onfido/react-native-sdk#4-adding-the-onfido-react-native-sdk-to-your-project), the application will not compile because of this error that is located in the `gradle.publish` file:

`Cannot set the value of property ‘id’ of type java.lang.String using an instance of type org.apache.groovy.json.internal.LazyMap`

Configuration:
- onfido sdk version: 4.0.0
- gradle: 7.0.2
- react-native version: 0.65.1
- buildToolsVersion: "30.0.2"
- minSdkVersion: 21
- compileSdkVersion: 31
- targetSdkVersion: 30
- ndkVersion: "21.4.7075529"

steps to reproduce:

- `create-react-native-app my-project`
- `cd my-project`
-  `npm install @onfido/react-native-sdk --save`
- `npm --prefix node_modules/@onfido/react-native-sdk/ run updateBuildGradle`
- `npm run android`

I perform these steps also in an existing project getting the same error.

**Comment by ramprasad-parajuli** [comment]
@andreaSimonePorceddu thank you for reaching out.
You should be able to resolve the issue by tweaking some parts of the code as follows:
Change your local package in this location:
@onfido\react-native-sdk\android\publish.gradle file these lines (36-7):
Seems like packageJson.author is an object and not a string, id & name are required to get a string.

Like this:
id = packageJson.author.name
name = packageJson.author.name

Let me know if the above solution works for you!

**Comment by andreaSimonePorceddu** [comment]
@ramprasad-parajuli 
I've just created a pull request in order to fix this issue.
#61
