### ISSUE TITLE
iOS blinking issue 

### ISSUE THREAD

**Issue by kolyan94** [onfido/react-native-sdk#64]
After update 2.2.0 => 4.0.1 we found the blinking issue when calling `Onfido.start` with
`flowSteps: {
          welcome: false
`.
Looks like it still opens the welcome screen and automatically closes it. 
With `welcome: true` everything works nice, but we don't need the welcome screen. 
Not reproducible with a simulator.
Attachments: 

https://user-images.githubusercontent.com/20342067/153218589-5598588d-d1db-4d04-952c-9c2c2efd0df7.MP4

Thanks!

**Comment by ramprasad-parajuli** [comment]
@kolyan94 thank you for raising the issue with us. Could you please let us know whether the issue occurs with the iOS device only, or happens with both, Android and iOS devices?

**Comment by kushal-onfido** [comment]
Hi @kolyan94 Could you please confirm if the issue occurs with the iOS device only, or happens with both, Android and iOS devices?
Thanks!

**Comment by gurpreet-onfido** [comment]
Hello @kolyan94 

Due to no response from your side, we are closing this issue. Please feel free to reach out to us, with the requested information and we will take it from there.

Kind regards
Gurpreet Singh
