### ISSUE TITLE
Sdk not supported

### ISSUE THREAD

**Issue by ManpreetBhardwaj** [onfido/react-native-sdk#65]
Failed to build module 'Onfido'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.

**Comment by andra-radu** [comment]
@ManpreetBhardwaj Could you please confirm the SDK version you are using? we’ve moved in October to Xcode 13 in version 23.0.0. You might need change the SDK version used to get it compatible with you new Xcode version.

**Comment by ManpreetBhardwaj** [comment]
"@onfido/react-native-sdk": "^2.2.0",
  Event I have Updated the SDK to latest version

**Comment by gurpreet-onfido** [comment]
Hello @ManpreetBhardwaj Did you get a chance to look into the response shared by my colleague @mikeger?

Looking forward to your response.

**Comment by ManpreetBhardwaj** [comment]
Yes, thanks for the update this is working fine now, as I have latest machine having latest version. So for initial stage code is written with low version after update everything working fine.
