### ISSUE TITLE
Is it possible to add docType of POA as onfido-sdk-ui have?

### ISSUE THREAD

**Issue by alexmyshchyshyn** [onfido/react-native-sdk#78]
Hi. Thank you for the great SDK.

**Question**: 
Onfido SDK for the front-end which my company uses ( https://github.com/onfido/onfido-sdk-ui ) has the type `poa`. 
`This is the Proof of Address capture step. Users will be asked to select the issuing country of their document, the document type, and to provide images of their selected document. They will also have a chance to check the quality of the images before confirming. There are no custom options for this step.`

And I need to have the same at react native application. But `OnfidoDocumentType` don't have it. 
Can you please advise how I can reproduce this functionality?

**Comment by andra-radu** [comment]
@alexmyshchyshyn - You can achieve this using GENERIC document type. The only downside would be that GENERIC document type doesn't offer an optimised capture experience for a desired document type and also you will be required to capture front and back of the document. You won't be able to choose to only upload the front of the document.

If you upload a generic document, you will be able to create proof of address checks but you will need to mention which documents to be used for document and proof of address check as well. As per our [documentation](https://documentation.onfido.com/#create-check-request-body), by default, the Document report will use the most recently uploaded document.  
If the last (most recent) uploaded document is bank statement/ Building Society Statements, document report will use that for processing and it will be flagged for non supported. 
Please let us know if you have any questions.

**Comment by alexmyshchyshyn** [comment]
Hi, @andra-radu .

> If you upload a generic document, you will be able to create proof of address checks but you will need to mention which documents to be used for document and proof of address check as well.

Okay, I have selected GENERIC document type. I captured two sides of document, and get a response `{"document": {"back": {"id": "udj"}, "front": {"id": "udj2"}}}`

For our backend, I need a document type. 
With [Onfido SDK UI ](https://github.com/onfido/onfido-sdk-ui) I get a good response with a specified document ( type ). 
`{
   "document_front": {
      "id":"someid",
      "type":"government_letter",
      "side":"front",
      "variant":"standard"
   }
}`


Questions:
1. With GENERIC TYPE, how i can capture a document in A4 format?
2. How i can get the document type that I captured OR can I select this type before uploading?

**Comment by andra-radu** [comment]
Hi @alexmyshchyshyn - 

> With GENERIC TYPE, how i can capture a document in A4 format? 

In the same way as you would capture any other document as it doesn't offer an optimised capture experience for a desired document type.

Could you please confirm if  you are running the WebSDK in a WebView in a React Native App? The reason for which I'm asking is because WebView is not officially supported.

**Comment by gurpreet-onfido** [comment]
Hello there!

Due to lack of response, we are closing this thread. Please get in touch with us if you need any additional help.

Kind regards,
Gurpreet Singh
