### ISSUE TITLE
Update SDK to latest

### ISSUE THREAD

**Issue by pouriabagheri** [onfido/react-native-sdk#85]
any plans to update the react native SDK to lates android and iOS SDK ?

https://github.com/onfido/onfido-android-sdk/tree/12.2.0
https://github.com/onfido/onfido-ios-sdk/tree/25.0.0

**Comment by ramprasad-parajuli** [comment]
@pouriabagheri thank you for reaching out. We are planning to release a new version of the RN SDK with the latest versions of android and ios SDK by the end of June.

**Comment by gurpreet-onfido** [comment]
Hello Poorya,

Greetings for the day!

We have released a new version of our React Native SDK that supports:

Android 12.2.0 (up from 11.5.0)
iOS 25.1.0 (up from 24.6.0)

Please refer to the release notes here: https://github.com/onfido/react-native-sdk/releases/tag/v5.4.0

Kind regards
Gurpreet Singh
