### ISSUE TITLE
Please remove video from Onfido

### ISSUE THREAD

**Issue by OksanaHanailiuk** [onfido/react-native-sdk#86]
Please remove video from Onfido, because a man's daughter uploaded a video to Onfido by accident and wants it taken down. 

https://dashboard.onfido.com/applicant/dea5c1c6-9b8a-40a5-b54e-23d1a1fcf1ad/check/4c72b6bb-5b4f-410f-bc3a-af54dded13b0/videos

_Customer reference id_
wTKEupr8HQUU3mq719PR5R

Thank you in advance

**Comment by onfidosupportuser4** [comment]
Hi @OksanaHanailiuk 

Thanks for contacting us. Since this is not a react-native issue, could you please submit your request using Onfido's e-mail (client-support@onfido.com)?

Thanks.

**Comment by OksanaHanailiuk** [comment]
@onfidosupportuser4 thank you for such a quick response.
