### ISSUE TITLE
Build failed on Android build

### ISSUE THREAD

**Issue by filippobarcellos** [onfido/react-native-sdk#89]
Hey!

When building on Android I'm getting the error below. It works fine on IOS.

**What went wrong:**
```
error: static interface method invocations are not supported in -source 7
        OnfidoWorkflow.create(currentActivity)
                      ^
  (use -source 8 or higher to enable static interface method invocations)
```
```
Lib versions:
"react": "17.0.1",
"react-native": "0.64.3",
"@onfido/react-native-sdk": "^5.4.0"
```

Currently running on Java 8 compatibility so I'm struggle to find the problem here.

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by gurpreet-onfido** [comment]
Hello @filippobarcellos 

Thank you for reaching out to us and bringing this up.

We have been reported this issue already and we are already working on this. In the meantime, you can use the below workaround to resolve this at our end.

Add the following lines to your build.gradle:

```
compileOptions {
       sourceCompatibility JavaVersion.VERSION_1_8
       targetCompatibility JavaVersion.VERSION_1_8
   }
```

Please give this a try and let us know how it goes.

Kind regards
Gurpreet Singh

**Comment by filippobarcellos** [comment]
@1vinnie1 I have a workaround for now downgrading to v5.3.0.

**Comment by 1vinnie1** [comment]
> @1vinnie1 I have a workaround for now downgrading to v5.3.0.

thankyou for replied. It worked after downgrade to v5.3.0. but I have an issue when connect to our verify api. BE team told me it might relate to some location bug in v5.3.0. Have you got this error?

**Comment by gurpreet-onfido** [comment]
Hello all,

Greetings for the day!

I have confirmed with the team that the fix is now created and will be rolled out in the mid September React Native SDK release. 

Stay tuned!

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello all,

Greetings for the day!

We have released a new version of our React Native SDK that includes the fix for the reported issue. 

Kindly upgrade to the latest version of the React Native SDK.

Kind regards
Gurpreet Singh
