### ISSUE TITLE
Localisation does not work for android 

### ISSUE THREAD

**Issue by Nargle30** [onfido/react-native-sdk#9]
Hello,

When I use German language on Android device, the onfido flow is still in English.
On iOS German translation works perfectly.

I use:
"react-native": "0.61.0",
"react": "16.9.0",
"@onfido/react-native-sdk": "1.2.3",

And (in case this can be useful) to translate texts in our application that are not connected with onfido sdk we use:
"react-native-languages": "3.0.1",
"i18n-js": "3.1.0"

**Comment by gokhanaliccii** [comment]
Hi @Nargle30,

Sorry for the inconvenience, current react-native SDK uses  [5.5.0](https://github.com/onfido/onfido-android-sdk/releases/tag/5.5.0) android SDK which doesn't support out-of-the-box translation for German translations. German language being supported with [6.0.0](https://github.com/onfido/onfido-android-sdk/releases/tag/6.0.0). 

We're planning to release a new version for react-native SDK that uses the latest [android SDK](https://github.com/onfido/onfido-android-sdk/releases/tag/7.2.0) next week but there is also another option would add German language support on your end which is bumping up onfido SDK version `5.6.0` to `6.0.0` in [build gradle.file](https://github.com/onfido/react-native-sdk/blob/master/android/build.gradle#L104)

**Comment by gokhanaliccii** [comment]
Hi @Nargle30,

The new react-native version([1.3.0](https://github.com/onfido/react-native-sdk/blob/master/CHANGELOG.md#130---2020-08-04)) has been released which support the German language out of the box

**Comment by warrioru** [comment]
Hi @gokhanaliccii 

how are the default localizations used? 
I am trying to pass in the config a licalisation object but there are no constants for the language.

For example, to have Onfido in German for both iOs and Android,

localisation: 'de' could be used?

**Comment by gokhanaliccii** [comment]
Hi @warrioru 

Unfortunately, you can't supply a language code to start SDK as part of the react-native SDK. The language will be picked by phone language.

**Comment by gokhanaliccii** [comment]
@warrioru I'm closing the issue please let us if you think the issue not resolved

**Comment by Nargle30** [comment]
Thank you @gokhanaliccii ! 
Both options you provided work great.
