### ISSUE TITLE
Update React Version to latest(18.2.0)

### ISSUE THREAD

**Issue by jeet-dhandha** [onfido/react-native-sdk#90]
- Please update the react Version to latest(18.2.0).
https://github.com/onfido/react-native-sdk/blob/09de8c8868db3fe0d260250e86c8ce6cb16577e3/package.json#L65

**Comment by gurpreet-onfido** [comment]
Hello @jeet-dhandha 

Thank you for reaching out to us. 

I have logged a JIRA ticket for our engineering team to upgrade the React version. 

Will drop you a line here once this is done.

Let us know if there is anything else we can help you with.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @jeet-dhandha 

Could you please confirm us the impact of not having this (is there a particular feature they need in React 18.2, are you blocked from doing something, etc)? 

Looking forward to your response.

Kind regards
Gurpreet Singh

**Comment by jeet-dhandha** [comment]
We need React v18.2.0 as it fixes a child parent context issues and also due to limitation at v17 in your repo, the npm can not update to v18.2.0.

**Comment by roryabraham** [comment]
We are also running into this issue – it's preventing us from upgrading to npm 8 from npm 6. We are using React 18, but this package lists `react: '>=16.8.1 <=17.0.x'` as a peer dependency:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/47436092/185254120-cec8ea45-6ac7-4e3d-86ea-75ae8e0e80a5.png">

This leads to an unmet peer dependency error:

```
npm ERR! Could not resolve dependency: 
npm ERR! peer react@&quot;&gt;=16.8.1 &lt;=17.0.x&quot; from @onfido/react-native-sdk@5.4.0 
npm ERR! node_modules/@onfido/react-native-sdk 
npm ERR!   @onfido/react-native-sdk@&quot;^5.4.0&quot; from the root project 
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2 
npm ERR! node_modules/react 
npm ERR!   peer react@&quot;&gt;=16.8.1 &lt;=17.0.x&quot; from @onfido/react-native-sdk@5.4.0 
npm ERR!   node_modules/@onfido/react-native-sdk 
npm ERR!     @onfido/react-native-sdk@&quot;^5.4.0&quot; from the root project
```

**Comment by mickeyhead7** [comment]
+1 on this. The peer dependency restriction (`react: '>=16.8.1 <=17.0.x'`) blocks the upgrade to React 18 and the features that brings. Perhaps simply changing this to: `react: '>=16.8.1` temporarily will remove the upgrade path blockage?

We have forked your project temporarily [here](https://github.com/MichalCiesliczka/onfido-react-native-sdk) to get around our upgrade issue, and have found no problems with your library working on React 18. However, we do not want to have to maintain this for any length of time.

**Comment by jeet-dhandha** [comment]
@roryabraham i had created this issue for Expensify only 😄.

**Comment by mickeyhead7** [comment]
@gurpreet-onfido As a rationale for the impact of not having this: nobody can start a new react-native project using this package. You would have to create a project, then immediately downgrade to meet the peer dependency.

**Comment by gurpreet-onfido** [comment]
Hi everyone!

I had a word with our engineering team and they have confirmed that the task to update react version is now closed. 

A new release will be rolled out in couple of days now. 

Stay tuned!

Kind regards
Gurpreet Singh

**Comment by mickeyhead7** [comment]
Nice one @gurpreet-onfido, thanks for the update 👍

**Comment by gurpreet-onfido** [comment]
Hello all,

We have released a new version of our React Native SDK and this version includes:

Update the supported React version to the latest.

For more details, please refer this link: https://github.com/onfido/react-native-sdk/releases/tag/v6.0.0

Kindly upgrade the React Native SDK at your side.

Kind regards
Gurpreet Singh
