### ISSUE TITLE
[iOS] SDK doesn't generate dSYM to check source maps

### ISSUE THREAD

**Issue by pedpess** [onfido/react-native-sdk#91]
While uploading the source maps with dSYM to Bugsnag (our crash analytics tool), I noticed that the dSYM for Onfido is not included. That makes it impossible to see the stack trace of the issue in case there's a crash on Onfido's side.

May you folks please add it? I can help as a guinea pig to test it out if needed as well :)

Many thanks for considering my request.

**Comment by limnash-onfido** [comment]
Hi @pedpess , thanks for bringing this up. We are looking into it!

**Comment by limnash-onfido** [comment]
Hi @pedpess , could you let me know the Onfido iOS SDK version you are on?

**Comment by pedpess** [comment]
@limnash-onfido I'm using Onfido React Native v4.0.1 and the Pods version of iOS is v23.1.0

**Comment by limnash-onfido** [comment]
Hi @pedpess , dSYM was added to iOS v24.4.0 and above https://github.com/onfido/onfido-ios-sdk/releases/tag/24.4.0
This means that upgrading to the latest version would solve the issue.

**Comment by pedpess** [comment]
@limnash-onfido thanks. Checking your RN package that seems to be v5.2.0
https://github.com/onfido/react-native-sdk/releases/tag/v5.2.0

**Comment by limnash-onfido** [comment]
Hi @pedpess , yes this is correct!
