### ISSUE TITLE
Google Play Store Violation: Deadline August 30, 2022

### ISSUE THREAD

**Issue by damrem** [onfido/react-native-sdk#93]
The issue is directly linked to this issue in Android SDK : https://github.com/onfido/onfido-android-sdk/issues/207

Can you please upgrade dependency on [onfido-android-sdk](https://github.com/onfido/onfido-android-sdk) to 12.2.2 and publish a new version of [react-native-sdk](https://github.com/onfido/react-native-sdk)?

**Comment by gurpreet-onfido** [comment]
Hello @damrem 

Greetings for the day!

We have released the latest version of the React Native SDK that supports Android SDK version 13.0.0 (up from 12.2.0).

Please let us know if anything additional is needed from our side.

Kind regards
Gurpreet Singh
