### ISSUE TITLE
 _initialize_OnfidoSdk in OnfidoSdk

### ISSUE THREAD

**Issue by aurelkpr** [onfido/react-native-sdk#96]
After adding [lottie-react-native: ^5.1.4](https://github.com/lottie-react-native/lottie-react-native), I get this error on iOS build

React Native env:
"react": "17.0.2",
"react-native": "0.68.3",
"@onfido/react-native-sdk": "^6.0.0",
"lottie-react-native": "^5.1.4",

▸ Processing onfido-react-native-sdk-Info.plist
▸ Compiling RCTAlertController.m
▸ Linking onfido_react_native_sdk
❌  Undefined symbols for architecture x86_64
> Symbol: _RCTRegisterModule
> Referenced from: _initialize_OnfidoSdk in OnfidoSdk-c4b6a3ec98eeec62eb18464ddf1ca4f1.o
❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by aurelkpr** [comment]
Adding the 'React-Core' may fix the issue
![image](https://user-images.githubusercontent.com/28559413/196152781-2cce1801-7334-4d40-a166-0e610bbd2879.png)

**Comment by limnash-onfido** [comment]
Hi @aurelkpr , thanks for raising this. We will come back to you soon with an update!

**Comment by keremgund** [comment]
Hey @aurelkpr ,
I've just pushed [new branch](https://github.com/onfido/react-native-sdk/tree/lottie-example ) to demonstrate lottie can work along with Onfido SDK without problem.

Thanks,
Kerem
